name: car_rental_system_fyp
description: "car rental system fyp"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0

  latlong2: ^0.9.1


  image_picker: ^1.0.0
  file_picker: ^10.3.10

  geolocator: ^10.1.0

  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.12.0


  # UI & Utilities
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2

  # Form validation
  email_validator: ^3.0.0

  # Email sending
  mailer: ^6.0.1

  # Deep linking for verification links
  app_links: ^6.4.1

  # HTTP client for API calls
  http: ^1.2.0

  # Firebase AI
  firebase_core: ^4.1.1
  firebase_ai: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

