// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjvMvGM_ir8Zzw5STrU-StBkg8Zwl8VU',
    appId: '1:936576807131:web:70e68da7b7de9c47509cfe',
    messagingSenderId: '936576807131',
    projectId: 'fypp-bb979',
    authDomain: 'fypp-bb979.firebaseapp.com',
    storageBucket: 'fypp-bb979.firebasestorage.app',
    measurementId: 'G-044C9G50FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXiP9isBAZ79s_nTKIHN6eH2sfmHMbyk',
    appId: '1:936576807131:android:0f209ef250b816a2509cfe',
    messagingSenderId: '936576807131',
    projectId: 'fypp-bb979',
    storageBucket: 'fypp-bb979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAG3KuluQkU7IeEfFc8B-zH2kb0nhk86M',
    appId: '1:936576807131:ios:b9439970f11e6b40509cfe',
    messagingSenderId: '936576807131',
    projectId: 'fypp-bb979',
    storageBucket: 'fypp-bb979.firebasestorage.app',
    iosBundleId: 'com.example.carRentalSystemFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAG3KuluQkU7IeEfFc8B-zH2kb0nhk86M',
    appId: '1:936576807131:ios:b9439970f11e6b40509cfe',
    messagingSenderId: '936576807131',
    projectId: 'fypp-bb979',
    storageBucket: 'fypp-bb979.firebasestorage.app',
    iosBundleId: 'com.example.carRentalSystemFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcjvMvGM_ir8Zzw5STrU-StBkg8Zwl8VU',
    appId: '1:936576807131:web:9f1da3e6957672da509cfe',
    messagingSenderId: '936576807131',
    projectId: 'fypp-bb979',
    authDomain: 'fypp-bb979.firebaseapp.com',
    storageBucket: 'fypp-bb979.firebasestorage.app',
    measurementId: 'G-P87SJX96K2',
  );
}
